
import 'package:flutter/cupertino.dart';

class Trip with ChangeNotifier {
  String id; // Added field for autogenerated ID
  DateTime start;
  DateTime end;
  String destination;
  Flight flight;
  Hotel hotel;
  int budget;
  List<Expense>? expenses;
  List<Packing_List> ?packing_list;

  Trip({
    this.id = '', // Initialize the ID as an empty string
    required this.start,
    required this.end,
    required this.destination,
    required this.flight,
    required this.hotel,
    required this.budget,
    this.expenses,
    this.packing_list,
  });
}

class Packing_List{
  String name;
  bool isPacked;

  Packing_List({required this.name, this.isPacked = false});

}
class Expense {
  String category;
  int amount;

  Expense({required this.category, required this.amount});
}

class Flight {
  String departure;
  String arrival;
  String flightNum;

  Flight({
    required this.departure,
    required this.arrival,
    required this.flightNum,
  });
}

class Hotel {
  DateTime checkIn;
  DateTime checkOut;
  int roomNum;

  Hotel({
    required this.checkIn,
    required this.checkOut,
    required this.roomNum,
  });
}



